#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RenanBandeira.Resource", IsApplication=true)]

namespace RenanBandeira
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::RenanBandeira.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int activity_padding = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int todo_count_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int active_item_checkbox = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int clear_completed_button = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int filter_active_button = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int filter_all_button = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int filter_inactive_button = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int item_content_edittext = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int item_delete_button = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int items_count_textview = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int todo_item_edittext = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int todo_listview = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int button_add = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int button_clear_completed = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int button_delete = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int button_edit = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int button_filter_active = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int button_filter_all = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int button_filter_inactive = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int hint_todo_item_add = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int info_todo_count = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int title_filter = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
