#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RenanBandeira.Resource", IsApplication=true)]

namespace RenanBandeira
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::RenanBandeira.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int accent = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int background = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int divider = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int icons = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary_dark = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int primary_light = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int primary_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int secondary_text = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_padding = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int todo_count_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int active_item_checkbox = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int clear_completed_button = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int filter_active_button = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int filter_all_button = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int filter_inactive_button = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int footer_layout = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int header_layout = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int item_content_edittext = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int item_delete_button = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int items_count_textview = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int todo_item_edittext = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int todo_listview = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int button_add = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int button_clear_completed = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int button_delete = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int button_edit = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int button_filter_active = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int button_filter_all = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int button_filter_inactive = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int hint_todo_item_add = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int info_todo_count = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int title_filter = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBarTitleText = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int ToDoListTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Widget_Styled_ActionBar = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
